#!/bin/busybox sh
set -e

export PATH=/bin:/sbin

mount -t proc none /proc

RESET_FACTORY=0

for arg in $(cat /proc/cmdline); do
  case "$arg" in
    thinbox.reset=1)
      RESET_FACTORY=1
      ;;
  esac
done

mount -t sysfs none /sys
mount -t devtmpfs none /dev

echo "[initramfs] Starting Thin Box init..."

mkdir -p /newroot

# Aguarda dispositivos
sleep 2

# Ajuste conforme device real (QEMU: /dev/vda)
ROOTDEV="/dev/vda2"

mount "$ROOTDEV" /newroot

# Mount squashfs
mkdir -p /newroot/lower
mount -t squashfs /newroot/rootfs.squashfs /newroot/lower

# Overlay
mkdir -p /newroot/{upper,work,root}

RESET_FLAG="/rw/FACTORY_RESET"

mount -t overlay overlay \
  -o lowerdir=/newroot/lower,upperdir=/newroot/upper,workdir=/newroot/work \
  /newroot/root

echo "[initramfs] Switching root..."

exec switch_root /newroot/root /sbin/init
